#!/usr/bin/env Rscript

# Technical smoke-test pilot for brainMapR bivariate SumR2 regression.
#
# Purpose:
#   Run the AD UKB40k x hypertension pilot while GFA::ldsc_rg() is unavailable
#   in the installed CRAN GFA_1.0.5. This script does not modify raw BWAS files
#   or installed R packages.
#
# Inputs:
#   outputs/pilot/derived_inputs/BWAS_Alzheimer_40k_vtxName.Probe.linear
#   outputs/pilot/derived_inputs/sstat_FS_All_moda_total_hyperTension.Probe.linear
#
# Outputs:
#   outputs/pilot/AD_UKB40k__hyperTension_local_ldsc_rg/
#
# WARNING:
#   This uses a local non-official ldsc_rg shim because GFA::ldsc_rg() is
#   unavailable. Do not use for final interpretation until validated.

options(stringsAsFactors = FALSE)

warning_msg <- paste(
  "This uses a local non-official ldsc_rg shim because GFA::ldsc_rg() is",
  "unavailable. Do not use for final interpretation until validated."
)

message("WARNING: ", warning_msg)

suppressPackageStartupMessages({
  library(brainMapR)
  library(vroom)
  library(plyr)
})

pilot_inputs <- list(
  inputPath = c("outputs/pilot/derived_inputs/", "outputs/pilot/derived_inputs/"),
  bwasFile = c(
    "BWAS_Alzheimer_40k_vtxName.Probe.linear",
    "sstat_FS_All_moda_total_hyperTension.Probe.linear"
  ),
  refPanel = c("AVERAGE"),
  bwasSampleSize = c("NMISS", "NMISS"),
  outputPath = "outputs/pilot/AD_UKB40k__hyperTension_local_ldsc_rg"
)

dir.create(pilot_inputs$outputPath, recursive = TRUE, showWarnings = FALSE)

writeLines(
  c(
    "# Local ldsc_rg shim pilot output",
    "",
    paste("WARNING:", warning_msg),
    "",
    "This directory was generated by scripts/03_run_brainMapR_pilot_local_ldsc_rg.R.",
    "The local LDSC implementation is intended for pipeline validation only.",
    "Do not interpret these outputs as final scientific results until validated",
    "against the original GFA::ldsc_rg() implementation expected by brainMapR."
  ),
  file.path(pilot_inputs$outputPath, "README_local_ldsc_rg_warning.md")
)

required_columns <- c("Probe", "b", "se", "p")

read_sumstats <- function(path) {
  if (!file.exists(path)) {
    stop("Input file does not exist: ", path)
  }
  if (file.info(path)$size == 0) {
    stop("Input file is empty: ", path)
  }
  vroom::vroom(path, show_col_types = FALSE, progress = FALSE)
}

validate_sumstats <- function(dat, path, require_nmiss = TRUE) {
  missing_columns <- setdiff(required_columns, names(dat))
  if (length(missing_columns) > 0) {
    stop(
      "Missing required columns in ", path, ": ",
      paste(missing_columns, collapse = ", ")
    )
  }
  if (require_nmiss && !"NMISS" %in% names(dat)) {
    stop("Missing required sample-size column NMISS in ", path)
  }
  invisible(TRUE)
}

get_brainmapr_function <- function(name) {
  if (exists(name, envir = asNamespace("brainMapR"), inherits = FALSE)) {
    get(name, envir = asNamespace("brainMapR"), inherits = FALSE)
  } else if (exists(name, mode = "function")) {
    get(name, mode = "function")
  } else {
    stop("Could not find brainMapR helper function: ", name)
  }
}

formatBWAScortical <- get_brainmapr_function("formatBWAScortical")
formatBWASsubcortical <- get_brainmapr_function("formatBWASsubcortical")

as_numeric_vector <- function(x) {
  as.numeric(unlist(x, use.names = FALSE))
}

resolve_sample_size <- function(dat, requested, suffix) {
  numeric_value <- suppressWarnings(as.numeric(requested))
  if (!is.na(numeric_value)) {
    return(numeric_value)
  }

  candidates <- unique(c(requested, paste0(requested, suffix)))
  matched <- candidates[candidates %in% names(dat)]
  if (length(matched) == 0) {
    stop(
      "Sample-size column not found. Requested ", requested,
      " with suffix ", suffix, ". Available columns include: ",
      paste(head(names(dat), 30), collapse = ", ")
    )
  }

  value <- as_numeric_vector(dat[[matched[1]]])[1]
  if (!is.finite(value) || is.na(value) || value <= 0) {
    stop("Invalid sample size from column ", matched[1], ": ", value)
  }
  value
}

weighted_lm_iterative <- function(x, y, ld_score, include_intercept = TRUE,
                                  max_iter = 100, tol = 1e-6) {
  keep <- is.finite(x) & is.finite(y) & is.finite(ld_score)
  x <- x[keep]
  y <- y[keep]
  ld_score <- ld_score[keep]

  if (length(y) < 10) {
    stop("Too few observations for weighted regression.")
  }

  w_ld <- pmax(ld_score, 1)
  pred_old <- pmax(abs(y), 1e-8)
  coef <- c(`(Intercept)` = 0, slope = 0)

  for (iter in seq_len(max_iter)) {
    weights <- 1 / (pmax(pred_old^2 * w_ld, 1e-12))
    design <- if (include_intercept) cbind(1, x) else matrix(x, ncol = 1)
    fit <- stats::lm.wfit(x = design, y = y, w = weights)
    coef_raw <- as.numeric(fit$coefficients)

    if (include_intercept) {
      coef <- c(`(Intercept)` = coef_raw[1], slope = coef_raw[2])
      pred_new <- as.numeric(design %*% coef_raw)
    } else {
      coef <- c(`(Intercept)` = 0, slope = coef_raw[1])
      pred_new <- as.numeric(design %*% coef_raw)
    }

    if (max(abs(pred_new - pred_old), na.rm = TRUE) < tol) {
      break
    }
    pred_old <- pmax(abs(pred_new), 1e-8)
  }

  coef
}

estimate_ldsc_components <- function(ld_score, ld_size, z1, z2,
                                     sample_size_1, sample_size_2,
                                     chi2_thr2 = 80) {
  chi2_1 <- z1^2
  chi2_2 <- z2^2
  keep <- is.finite(ld_score) &
    is.finite(z1) & is.finite(z2) &
    is.finite(chi2_1) & is.finite(chi2_2) &
    chi2_1 < chi2_thr2 & chi2_2 < chi2_thr2

  if (sum(keep) < 100) {
    stop("Too few finite vertices after chi-square filtering.")
  }

  ld_score <- ld_score[keep]
  z1 <- z1[keep]
  z2 <- z2[keep]
  chi2_1 <- chi2_1[keep]
  chi2_2 <- chi2_2[keep]

  x1 <- ld_score / ld_size * sample_size_1
  x2 <- ld_score / ld_size * sample_size_2
  x12 <- ld_score / ld_size * sqrt(sample_size_1 * sample_size_2)

  fit1 <- weighted_lm_iterative(x1, chi2_1, ld_score, include_intercept = TRUE)
  fit2 <- weighted_lm_iterative(x2, chi2_2, ld_score, include_intercept = TRUE)
  fit12 <- weighted_lm_iterative(x12, z1 * z2, ld_score, include_intercept = TRUE)

  m2_1 <- unname(fit1["slope"])
  m2_2 <- unname(fit2["slope"])
  braincov <- unname(fit12["slope"])
  rGM <- if (is.finite(m2_1) && is.finite(m2_2) && m2_1 > 0 && m2_2 > 0) {
    braincov / sqrt(m2_1 * m2_2)
  } else {
    NA_real_
  }

  c(
    int = unname(fit12["(Intercept)"]),
    braincov = braincov,
    t1_int = unname(fit1["(Intercept)"]),
    t2_int = unname(fit2["(Intercept)"]),
    m2_1 = m2_1,
    m2_2 = m2_2,
    rGM = rGM
  )
}

jackknife_se <- function(pseudovalues, estimate_j) {
  h_blocks <- nrow(pseudovalues)
  sqrt(colMeans((pseudovalues - rep(estimate_j, each = h_blocks))^2 / (h_blocks - 1)))
}

local_ldsc_rg <- function(ld_score, ld_size, z1, z2, sample_size_1, sample_size_2,
                          blocks = 200, chi2_thr2 = 80) {
  ld_score <- as_numeric_vector(ld_score)
  z1 <- as_numeric_vector(z1)
  z2 <- as_numeric_vector(z2)
  sample_size_1 <- as.numeric(sample_size_1)[1]
  sample_size_2 <- as.numeric(sample_size_2)[1]

  keep <- is.finite(ld_score) & is.finite(z1) & is.finite(z2)
  ld_score <- ld_score[keep]
  z1 <- z1[keep]
  z2 <- z2[keep]

  n_vertices <- length(ld_score)
  if (n_vertices < 100) {
    stop("Too few vertices for local_ldsc_rg().")
  }

  block_count <- min(blocks, n_vertices)
  block_id <- ceiling(seq_len(n_vertices) / n_vertices * block_count)
  block_id[block_id < 1] <- 1
  block_id[block_id > block_count] <- block_count
  h_blocks <- length(unique(block_id))

  if (h_blocks < 2) {
    stop("At least two jackknife blocks are required.")
  }

  full_estimate <- estimate_ldsc_components(
    ld_score = ld_score,
    ld_size = ld_size,
    z1 = z1,
    z2 = z2,
    sample_size_1 = sample_size_1,
    sample_size_2 = sample_size_2,
    chi2_thr2 = chi2_thr2
  )

  leave_one_out <- matrix(
    NA_real_,
    nrow = h_blocks,
    ncol = length(full_estimate),
    dimnames = list(NULL, names(full_estimate))
  )

  for (block in seq_len(h_blocks)) {
    use <- block_id != block
    leave_one_out[block, ] <- estimate_ldsc_components(
      ld_score = ld_score[use],
      ld_size = sum(use),
      z1 = z1[use],
      z2 = z2[use],
      sample_size_1 = sample_size_1,
      sample_size_2 = sample_size_2,
      chi2_thr2 = chi2_thr2
    )
  }

  pseudovalues <- h_blocks *
    matrix(rep(full_estimate, each = h_blocks), nrow = h_blocks) -
    (h_blocks - 1) * leave_one_out
  colnames(pseudovalues) <- names(full_estimate)

  estimate_j <- colMeans(pseudovalues, na.rm = TRUE)
  se_j <- jackknife_se(pseudovalues, estimate_j)

  out <- c(
    int = estimate_j["int"],
    int_se = se_j["int"],
    braincov = estimate_j["braincov"],
    braincov_se = se_j["braincov"],
    t1_int = estimate_j["t1_int"],
    t2_int = estimate_j["t2_int"],
    m2_1 = estimate_j["m2_1"],
    m2_1_se = se_j["m2_1"],
    m2_2 = estimate_j["m2_2"],
    m2_2_se = se_j["m2_2"],
    rGM = estimate_j["rGM"],
    rGM_se = se_j["rGM"]
  )

  names(out) <- c(
    "int", "int_se",
    "braincov", "braincov_se",
    "t1_int", "t2_int",
    "m2_1", "m2_1_se",
    "m2_2", "m2_2_se",
    "rGM", "rGM_se"
  )
  out
}

make_result_row <- function(panel, ldres) {
  pvalue_1 <- 2 * stats::pnorm(-abs(ldres["m2_1"] / ldres["m2_1_se"]))
  pvalue_2 <- 2 * stats::pnorm(-abs(ldres["m2_2"] / ldres["m2_2_se"]))
  pvalue_rGM <- 2 * stats::pnorm(-abs(ldres["rGM"] / ldres["rGM_se"]))

  data.frame(
    sumR2RefPanel = panel,
    int = ldres["int"],
    int_se = ldres["int_se"],
    braincov = ldres["braincov"],
    braincov_se = ldres["braincov_se"],
    t1_int = ldres["t1_int"],
    t2_int = ldres["t2_int"],
    m2_1 = ldres["m2_1"],
    m2_1_se = ldres["m2_1_se"],
    pvalue_1 = pvalue_1,
    m2_1_CI_lb = ldres["m2_1"] - 1.96 * ldres["m2_1_se"],
    m2_1_CI_ub = ldres["m2_1"] + 1.96 * ldres["m2_1_se"],
    m2_2 = ldres["m2_2"],
    m2_2_se = ldres["m2_2_se"],
    pvalue_2 = pvalue_2,
    m2_2_CI_lb = ldres["m2_2"] - 1.96 * ldres["m2_2_se"],
    m2_2_CI_ub = ldres["m2_2"] + 1.96 * ldres["m2_2_se"],
    rGM = ldres["rGM"],
    rGM_se = ldres["rGM_se"],
    pvalue_rGM = pvalue_rGM,
    rGM_CI_lb = ldres["rGM"] - 1.96 * ldres["rGM_se"],
    rGM_CI_ub = ldres["rGM"] + 1.96 * ldres["rGM_se"],
    check.names = FALSE
  )
}

message("Reading pilot inputs.")
path1 <- paste0(pilot_inputs$inputPath[1], pilot_inputs$bwasFile[1])
path2 <- paste0(pilot_inputs$inputPath[2], pilot_inputs$bwasFile[2])

bwas1_raw <- read_sumstats(path1)
bwas2_raw <- read_sumstats(path2)
validate_sumstats(bwas1_raw, path1, require_nmiss = TRUE)
validate_sumstats(bwas2_raw, path2, require_nmiss = TRUE)

message("Annotating first BWAS with brainMapR reference handling.")
bwas1_annotated <- NULL
for (mod in c("thickness", "area", "thick", "LogJacs")) {
  for (hemi in c("lh", "rh")) {
    formatted <- if (mod %in% c("area", "thickness")) {
      formatBWAScortical(BWASsumstat = bwas1_raw, hemi = hemi, mod = mod)
    } else {
      formatBWASsubcortical(BWASsumstat = bwas1_raw, hemi = hemi, mod = mod)
    }
    formatted$CHI2 <- (formatted$b / formatted$se)^2
    bwas1_annotated <- plyr::rbind.fill(bwas1_annotated, formatted)
  }
}

message("Merging annotated first BWAS with second BWAS by Probe.")
bwas_merged <- merge(
  bwas1_annotated,
  bwas2_raw,
  by = "Probe",
  suffixes = c("_1", "_2")
)

if (!all(c("b_1", "se_1", "p_1", "b_2", "se_2", "p_2") %in% names(bwas_merged))) {
  stop("Merged BWAS does not contain expected suffixed b/se/p columns.")
}

bwas_merged$z_1 <- as_numeric_vector(bwas_merged$b_1) / as_numeric_vector(bwas_merged$se_1)
bwas_merged$z_2 <- as_numeric_vector(bwas_merged$b_2) / as_numeric_vector(bwas_merged$se_2)

missing_assoc <- is.na(bwas_merged$p_1) | is.na(bwas_merged$p_2)
if (any(missing_assoc)) {
  bwas_merged <- bwas_merged[!missing_assoc, ]
}

sample_size_1 <- resolve_sample_size(
  bwas_merged,
  requested = pilot_inputs$bwasSampleSize[1],
  suffix = "_1"
)
sample_size_2 <- resolve_sample_size(
  bwas_merged,
  requested = pilot_inputs$bwasSampleSize[2],
  suffix = "_2"
)

message("Sample size 1: ", sample_size_1)
message("Sample size 2: ", sample_size_2)

results <- NULL
for (panel in pilot_inputs$refPanel) {
  sumr2_col <- paste0("SumR2_", panel)
  if (!sumr2_col %in% names(bwas_merged)) {
    stop("Reference panel column not found after annotation: ", sumr2_col)
  }

  panel_dat <- bwas_merged[!is.na(bwas_merged[[sumr2_col]]), ]
  message(
    "Estimating rGM using local ldsc_rg shim. Using ",
    nrow(panel_dat), " vertices and SumR2 from reference panel: ", panel
  )

  ldres <- local_ldsc_rg(
    ld_score = panel_dat[[sumr2_col]],
    ld_size = nrow(panel_dat),
    z1 = panel_dat$z_1,
    z2 = panel_dat$z_2,
    sample_size_1 = sample_size_1,
    sample_size_2 = sample_size_2,
    blocks = 200,
    chi2_thr2 = 80
  )

  results <- rbind(results, make_result_row(panel, ldres))
}

output_file <- file.path(
  pilot_inputs$outputPath,
  "SumR2_regression_bivariate_local_ldsc_rg.rsq"
)
write.table(results, output_file, col.names = TRUE, row.names = FALSE, quote = FALSE)

message("Wrote output: ", output_file)
message("WARNING: ", warning_msg)
print(results)
sessionInfo()
